# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_remove_skill_specialization'),
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='skills',
            field=models.ManyToManyField(to='skill.Skill'),
        ),
    ]
