# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialization', '0002_specialization_in_wishlist_of_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='in_wishlist_of_users',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
