# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialization', '0003_specialization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
