# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialization', '0003_auto_20160713_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
