# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
