# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_skill_short_description'),
        ('quiz', '0002_auto_20160719_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=100)),
                ('answer', models.CharField(blank=True, max_length=100)),
                ('answer1', models.CharField(blank=True, max_length=100)),
                ('answer2', models.CharField(blank=True, max_length=100)),
                ('answer3', models.CharField(blank=True, max_length=100)),
                ('skill', models.ManyToManyField(blank=True, to='skill.Skill')),
            ],
        ),
    ]
