# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=200)),
                ('profession_field', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=200)),
                ('user_last_name', models.CharField(max_length=200)),
                ('user_login_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_university', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='testuser',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.TestUserProfile'),
        ),
    ]
