# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 27, 9, 1, 2, 741368), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='task_descriptino',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
