# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 10, 27, 48, 202790, tzinfo=utc), verbose_name='date published'),
        ),
    ]
