# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 8, 29, 55, 559644), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='task_descriptino',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
