# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_spec_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.wishSpec'),
        ),
    ]
