# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='task',
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='vacancies',
            field=models.ManyToManyField(blank=True, to='company.Vacancy'),
        ),
    ]
