# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160530_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='passed_skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.TestSkill'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 6, 25, 11, 206435, tzinfo=utc), verbose_name='date published'),
        ),
    ]
