# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160526_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 8, 55, 52, 610751), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='task_descriptino',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
