# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160527_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 27, 9, 31, 25, 797081), verbose_name='date published'),
        ),
    ]
