# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160713_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='passed_skills',
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='main_app.wishSpec'),
        ),
    ]
