# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160713_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='worked_at',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
