# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160527_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 5, 21, 15, 942142), verbose_name='date published'),
        ),
    ]
