# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20160601_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='passed_skills',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 6, 50, 15, 789255, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='AbstractUser',
        ),
    ]
