# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160526_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 9, 18, 48, 189467), verbose_name='date published'),
        ),
    ]
