# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_abstractuser_worked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
