# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20160526_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='testskill',
            name='skill_description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 27, 3, 48, 50, 419805), verbose_name='date published'),
        ),
    ]
