# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20160714_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='worked_at',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
