# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_skill_short_description'),
        ('main_app', '0007_auto_20160719_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='passed_skills',
            field=models.ManyToManyField(blank=True, to='skill.Skill'),
        ),
    ]
