# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment_to_task', models.TextField()),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=10000)),
                ('problem', models.TextField(default='', max_length=10000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('specialization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specialization.Specialization')),
            ],
        ),
    ]
