# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_in_spec',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
