# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 10, 4, 7, 928444), verbose_name='date published'),
        ),
    ]
