# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160603_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 17, 51, 41, 500), verbose_name='date published'),
        ),
    ]
