# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('required_skills', models.ManyToManyField(blank=True, to='skill.Skill')),
                ('task', models.ManyToManyField(blank=True, to='tasks.CompanyTask')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='QnA',
            field=models.ManyToManyField(to='company.QuestionAndAnswer'),
        ),
    ]
