# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='QnA',
            field=models.ManyToManyField(to='company.QuestionAndAnswer'),
        ),
    ]
