# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='wishlist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.WishList'),
        ),
    ]
