# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id_in_spec',
        ),
    ]
