# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='media_books',
            field=models.ManyToManyField(blank=True, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='media_video',
            field=models.ManyToManyField(blank=True, to='media.Video'),
        ),
    ]
