# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='media_books',
        ),
        migrations.AddField(
            model_name='skill',
            name='media_books',
            field=models.ManyToManyField(to='media.Book'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='media_video',
        ),
        migrations.AddField(
            model_name='skill',
            name='media_video',
            field=models.ManyToManyField(to='media.Video'),
        ),
    ]
