# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='id_in_spec',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
