# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0002_remove_skill_id_in_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='solved_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
