# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_remove_skill_id_in_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='spec_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Images/skill_logo'),
        ),
    ]
