# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skill_solved_users'),
        ('skill', '0003_skill_spec_logo'),
    ]

    operations = [
    ]
