# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20160706_1202'),
        ('skill', '0003_auto_20160706_1445'),
    ]

    operations = [
    ]
