# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='specialization',
        ),
    ]
