# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='short_description',
            field=models.TextField(blank='', max_length=250, null=True),
        ),
    ]
